server:
    port: 8080
spring:
    profiles:
        active: dev

    jade4j:
        caching: false

    dataSource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/blog?serverTimezone=UTC
      username: root
      password: Lilith123.

    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      hbm2ddl.auto: update
      show_sql: false

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400